INSERT INTO products 
	(id, title, imageUrl, description, price, category, recommended, discountPrice, createdAt, createdBy) 
VALUES 
	(1, 'Good Headphone', 'https://m.media-amazon.com/images/I/51rpbVmi9XL._AC_SL1200_.jpg', 'Sony’s lightest wireless noise canceling headband ever: Weighing just 192g, our lightest overhead wireless headphones with Noise Canceling yet, for incredible comfort without compromising on technology. DUAL NOISE SENSOR TECHNOLOGY: Take noise canceling to the next level with Sony’s Integrated Processor V1, so you can fully immerse yourself in the music.', 105.2, 'accessories', false, 95.2, now(), 'system'),
	(2, 'Amazing Book 2nd', 'https://m.media-amazon.com/images/I/81dmHMoJDjL._SL1500_.jpg', 'As organizations shift from monolithic applications to smaller, self-contained microservices, distributed systems have become more fine-grained. But developing these new systems brings its own host of problems. This expanded second edition takes a holistic view of topics that you need to consider when building, managing, and scaling microservices architectures.', 29.44, 'book', true, null, now(), 'system'),
	(3, 'Heavy Duty Laptop', 'https://m.media-amazon.com/images/I/61RJn0ofUsL._AC_SL1500_.jpg', 'Apple 2023 MacBook Pro Laptop M3 Max chip with 14‑core CPU, 30‑core GPU: Built for Apple Intelligence, 14.2-inch Liquid Retina XDR Display, 36GB Unified Memory, 1TB SSD Storage; Space Black.', 3060.52, 'laptop', true, 3000.52, now(), 'system'),
	(4, 'Smart Home Device', 'https://m.media-amazon.com/images/I/61TuF2ElKgL._AC_SL1000_.jpg', 'A sleek smart alarm clock with Alexa and big vibrant sound. Ready to help you wake up, wind down, and so much more. See time, weather, and song titles at a glance, control smart home devices, and more. Personalize your display with your favorite clock face and fun colors. Enjoy rich sound with clear vocals and deep bass. Just ask Alexa to play music, podcasts, and audiobooks. See song titles and touch to control your music.', 54.99, 'smart home', true, 50.99, now(), 'system'),
	(5, 'Gaming Console','https://m.media-amazon.com/images/I/31JaiPXYI8L.jpg', 'The PS5 console unleashes new gaming possibilities that you never anticipated. Experience lightning fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and an all-new generation of incredible PlayStation games.', 499.99, 'gaming', false, null, now(), 'system'),
	(6, 'Air Purifier', 'https://m.media-amazon.com/images/I/81sg9Om6feL._AC_SL1500_.jpg', 'The 3-in-1 air purifier with HEPA filter is perfect for allergy sufferers. The filter captures 99.97% of allergens including pet dander, dust mites and pollen. The Pet Pure is an antimicrobial agent added to the filter to inhibit the growth of mold, mildew and odor-causing bacteria on the surface of the filter.', 89.99, 'home', false, 85.99, now(), 'system'),
	(7, 'Gaming Projector', 'https://m.media-amazon.com/images/I/51iF9NXBN2L._AC_SL1001_.jpg', 'The Optoma GT1080HDR is a short throw gaming projector that features a 120Hz refresh rate for blur-free visuals and outstanding gaming experiences. The 8.4ms response time and enhanced gaming mode ensure quick response and maximum gaming performance.', 1446.99, 'gaming', false, null, now(), 'system'),
	(8, 'Black Myth Speaker', 'https://m.media-amazon.com/images/I/815nga8GBqL._AC_SL1500_.jpg', 'The Black Myth Speaker is a portable Bluetooth speaker that delivers powerful sound with deep bass. It features a sleek design and long battery life, making it perfect for on-the-go listening. The speaker is also water-resistant, so you can take it to the beach or pool without worry.', 99.99, 'audio', true, null, now(), 'system');
