INSERT INTO attributes 
	(id, productId, name, displayName, value)
VALUES
	(1, 1, 'color', 'Color', 'Black'),
	(2, 1, 'brand', 'Brand', 'Sony'),
	(3, 1, 'weight', 'Weight', '192g'),
	(4, 1, 'connectivity', 'Connectivity', 'Wireless'),
	(5, 1, 'noiseCanceling', 'Noise Canceling', 'Yes'),
	(6, 1, 'batteryLife', 'Battery Life', '30 hours'),
	(7, 1, 'warranty', 'Warranty', '1 year'),
	(8, 2, 'author', 'Author', 'Sam Newman'),
	(9, 2, 'pages', 'Pages', '464'),
	(10, 2, 'publisher', 'Publisher', 'O''Reilly Media'),
	(11, 2, 'language', 'Language', 'English'),
	(12, 2, 'isbn-10', 'ISBN-10', '1492042695'),
	(13, 2, 'isbn-13', 'ISBN-13', '978-1492042697'),
	(14, 2, 'featured', 'Featured', 'featured'),
	(15, 2, 'publishDt', 'Publish Date', 'October 26, 2021'),
	(16, 3, 'brand', 'Brand', 'Apple'),
	(17, 3, 'processor', 'Processor', 'M3 Max chip with 14‑core CPU'),
	(18, 3, 'gpu', 'GPU', '30‑core GPU'),
	(19, 3, 'display', 'Display', '14.2-inch Liquid Retina XDR Display'),
	(20, 3, 'memory', 'Memory', '36GB Unified Memory'),
	(21, 3, 'storage', 'Storage', '1TB SSD Storage'),
	(22, 3, 'color', 'Color', 'Space Black'),
	(23, 3, 'warranty', 'Warranty', '1 year'),
	(24, 4, 'sound', 'Sound Quality', 'Big Vibrant Sound'),
	(25, 4, 'color', 'Color', 'Black'),
	(26, 4, 'screen', 'Screen Size', 'capacity'),
	(27, 4, 'camera', 'Camera', 'No'),
	(28, 4, 'motionDetection', 'Motion Detection', 'Yes'),
	(29, 4, 'temperatureSensor', 'Temperature Sensor', 'No'),
	(30, 5, 'asin', 'ASIN', 'B0BMXYPFTK'),
	(31, 5, 'brand', 'Brand', 'Sony'),
	(32, 5, 'processor', 'Processor', 'AMD Ryzen Zen 2'),
	(33, 5, 'gpu', 'GPU', 'AMD Radeon RDNA 2'),
	(34, 5, 'memory', 'Memory', '16GB GDDR6'),
	(35, 5, 'storage', 'Storage', '825GB SSD'),
	(36, 5, 'color', 'Color', 'White'),
	(37, 5, 'warranty', 'Warranty', '1 year'),
	(38, 6, 'filter', 'Filter', 'HEPA'),
	(39, 6, 'color', 'Color', 'White'),
	(40, 6, 'warranty', 'Warranty', '1 year'),
	(41, 7, 'brand', 'Brand', 'Optoma'),
	(42, 7, 'resolution', 'Resolution', '1080p'),
	(43, 7, 'brightness', 'Brightness', '3800 lumens'),
	(44, 7, 'contrastRatio', 'Contrast Ratio', '50,000:1'),
	(45, 7, 'color', 'Color', 'White'),
	(46, 7, 'warranty', 'Warranty', '1 year'),
	(47, 8, 'color', 'Color', 'Black'),
	(48, 8, 'brand', 'Brand', 'Black Myth'),
	(49, 8, 'weight', 'Weight', '1.5 lbs'),
	(50, 8, 'connectivity', 'Connectivity', 'Bluetooth'),
	(51, 8, 'batteryLife', 'Battery Life', '10 hours'),
	(52, 8, 'waterResistance', 'Water Resistance', 'Yes'),
	(53, 8, 'warranty', 'Warranty', '1 year'),
	(54, 8, 'featured', 'Featured', 'featured');